### ISSUE TITLE
Lack of development ;n;

### ISSUE THREAD

**Issue by Sidd-Dino** [Sidd-Dino/bte#2]
Sorry that the project has been untouched for quite a while. I've been facing mental health issues lately and, I can't bring myself to work on any projects nowadays. The project isn't dead. It's on hold, sorry, guys.

**Comment by Sidd-Dino** [comment]
I'm back lads \o/

**Comment by 0730kev** [comment]
hope you're fine!
this project is very promising like fff is
hope you add more features like cut, copy line, Home key!
